"""empty message

Revision ID: 499a484131b0
Revises: 
Create Date: 2017-03-15 14:18:40.445965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499a484131b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ord')
    op.alter_column('ORDERITEMS', 'asin',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ORDERITEMS', 'orderItemId',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ORDERITEMS', 'sellerSKU',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'ORDERITEMS', type_='foreignkey')
    op.drop_column('ORDERITEMS', 'inventory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ORDERITEMS', sa.Column('inventory_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'ORDERITEMS', 'INVENTORY', ['inventory_id'], ['id'])
    op.alter_column('ORDERITEMS', 'sellerSKU',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ORDERITEMS', 'orderItemId',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ORDERITEMS', 'asin',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('ord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asin', sa.TEXT(), nullable=True),
    sa.Column('supplier', sa.TEXT(), nullable=False),
    sa.Column('sellerSKU', sa.TEXT(), nullable=True),
    sa.Column('orderItemId', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('quantityShipped', sa.INTEGER(), nullable=True),
    sa.Column('itemPriceCurrency', sa.TEXT(), nullable=True),
    sa.Column('itemPrice', sa.FLOAT(), nullable=True),
    sa.Column('shippingPrice', sa.FLOAT(), nullable=True),
    sa.Column('giftWrapPrice', sa.FLOAT(), nullable=True),
    sa.Column('itemTax', sa.FLOAT(), nullable=True),
    sa.Column('shippingTax', sa.FLOAT(), nullable=True),
    sa.Column('giftWrapTax', sa.FLOAT(), nullable=True),
    sa.Column('shippingDiscount', sa.FLOAT(), nullable=True),
    sa.Column('promotionDiscount', sa.FLOAT(), nullable=True),
    sa.Column('inventory_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
